[env]
CUDA_TOOLKIT_PATH = { value = "/opt/cuda", relative = false }
CUTILE_TILEIRAS_PATH = { value = "/opt/cuda/bin/tileiras", relative = false }
RUSTFLAGS = { value = "-C target-cpu=native", relative = false }
